version: '3.3'

volumes:
  db_data:
  media:
  static:

services:
  db:
    container_name: foodgram-db
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ../.env

  backend:
    container_name: foodgram-back
    image: kateschka/foodgram_backend:latest
    env_file:
      - ../.env
    depends_on:
      - db
    volumes:
      - media:/app/media
      - static:/app/backend_static
    restart: always


  frontend:
    container_name: foodgram-front
    image: kateschka/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "9000:80"
    volumes:
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/media
      - static:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
