MAX_USER_FIRST_NAME_LENGTH = 150
MAX_USER_LAST_NAME_LENGTH = 150
MAX_USER_EMAIL_LENGTH = 254
MAX_USER_USERNAME_LENGTH = 150

MAX_TAG_NAME_LENGTH = 32
MAX_TAG_SLUG_LENGTH = 32

MAX_INGREDIENT_NAME_LENGTH = 128
MAX_INGREDIENT_MEASUREMENT_UNIT_LENGTH = 64

MAX_RECIPE_NAME_LENGTH = 256

MAX_SHORT_LINK_LENGTH = 10
