# Generated by Django 4.2 on 2025-04-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_follow_options_alter_follow_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Аватар пользователя', upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
